name: Jira New Issue

on:
  issues:
    types:
      - opened
jobs:
  login:    
    runs-on: ubuntu-latest
    steps:
      - name: Login
        uses: atlassian/gajira-login@v3
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
          
  create:
    if: github.event.action == 'opened'
    runs-on: ubuntu-latest
    needs: login
    steps:          
      - name: Create
        id: create
        uses: atlassian/gajira-create@v3
        with:
          project: MO
          issuetype: Task
          summary: ${{ github.event.issue.title }}
          description: ${{ github.event.issue.body }}
          
      - name: Log created issue
        run: echo "Issue ${{ steps.create.outputs.issue }} was created"
