name: PHP Codeception Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  tests:
    uses: humhub/actions/.github/workflows/module-tests-develop.yml@main
    with:
      module-id: gamecenter
      install-composer: true
