name: PHP Codeception Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

jobs:
  tests:
    uses: Matchbook-One/.github/.github/workflows/module-tests-develop.yml@main
    with:
      module-id: gamecenter
      php:
        - '8.1'
        - '8.2'
      install-composer: true
